/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smitch_smartswitch_fibonaccinative_FibLib */

#ifndef _Included_com_smitch_smartswitch_fibonaccinative_FibLib
#define _Included_com_smitch_smartswitch_fibonaccinative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smitch_smartswitch_fibonaccinative_FibLib
 * Method:    FibNativeRecursive
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_smitch_smartswitch_fibonaccinative_FibLib_FibNativeRecursive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_smitch_smartswitch_fibonaccinative_FibLib
 * Method:    FibNativeIterative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_smitch_smartswitch_fibonaccinative_FibLib_FibNativeIterative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
